apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-creds-cm
  annotations:
    kubernetes.io/description: |
      B64_AUTH=$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64)
data:
  config.json: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "$B64_AUTH"
        }
      }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--context=git://github.com/augustoliks/fakews.git"
        - "--destination=augustoliks/fakews"
      volumeMounts:
        - name: docker-creds
          mountPath: /kaniko/.docker/
          readOnly: true
  volumes:
    - name: docker-creds
      configMap:
        name: docker-creds-cm
